### ISSUE TITLE
Errors in version 78b7f0d

### ISSUE THREAD

**Issue by jacekpaszkowski** [Limych/ha-car_wash#3]
version 78b7f0d

**Configuration**
```yaml

- platform: car_wash
  weather: weather.dark_sky

```

**Describe the bug**

After last update i get errors in logs.

**Debug log**
2020-01-01 18:40:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.car_wash fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/config/custom_components/car_wash/binary_sensor.py", line 162, in async_update
    if isinstance(fc_date) == int:
TypeError: isinstance expected 2 arguments, got 1

**Comment by Limych** [comment]
Ooops, sorry :)
